#!/bin/bash
#SBATCH -J dmrg
#SBATCH --account=commons
#SBATCH --partition=commons
#SBATCH -e slurm-%x-%j.err
#SBATCH -o slurm-%x-%j.out
#SBATCH -t 24:00:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 128
#SBATCH --mem 0

module purge
ml GCC GCCcore Python pybind11 CMake imkl OpenMPI
pip install pyscf matplotlib
export PYTHONPATH=/scratch/mm207/block2/build:/scratch/mm207/block2:${PYTHONPATH}
python3 -u $1


